### ISSUE TITLE
Add egress rules to aws_security_group-s (prevent BC in 0.5.0)

### ISSUE THREAD

**Issue by radeksimko** [alphagov/tsuru-terraform#50]
I'm not sure which version are you guys using now, but looking at https://github.com/alphagov/tsuru-terraform/blob/f32ca77c7362c20241ce25f1e7e317757187746d/aws/security-groups.tf

you may want to know, that there's a behaviour change - Terraform is now removing the default egress rule: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#050-may-7-2015

so once you upgrade it, you may need to add the following:

``` ruby
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
```

**Comment by annashipman** [comment]
Hi @radeksimko, thanks a lot for this! We're on v0.4.2 so this is very useful to know, much appreciated!

**Comment by dcarley** [comment]
Tracking this in Pivotal now. Thanks again, @radeksimko!
